### ISSUE TITLE
"QuestionAttribute".".gid" not defined

### ISSUE THREAD

**Issue by Crossfor** [SondagesPro/pdfReport#2]
Hello!

I'm having some issue while using this plugin. Everything works fine if the survey is set to "question by question" or "all in one", but if it is set to "group by group" I get the error message **"QuestionAttribute".".gid" not defined**. Is there a way to solve this issue?

**My system configuration is:**
- LimeSurvey version: 3.28.59
- LimeSurvey build: 230517
- Operating system: Linux 5.4.0-150-generic [#167](tg://search_hashtag?hashtag=167)-Ubuntu SMP Mon May 15 17:35:05 UTC 2023 x86_64
- PHP version: 7.4.33
- Web server software: Apache
- Database driver: mysql
- Database driver version: mysqlnd 7.4.33
- Database server version: 8.0.33-0ubuntu0.20.04.2

Thank you very much!

**Comment by Shnoulle** [comment]
https://gitlab.com/SondagesPro/ExportAndStats/pdfReport/-/commit/83ef9fc63f2fb0c2bd0d4f676929f79c23d33e73

PS : it's better to use https://gitlab.com/SondagesPro/ExportAndStats/pdfReport/-/issues 

I didn't check github all days.

**Comment by Shnoulle** [comment]
Updated this night on dl.
